### ISSUE TITLE
How to limit the size of the map?

### ISSUE THREAD

**Issue by Changliu52** [ethz-asl/voxblox#182]
Thank you for sharing the code.
I am trying to use it for drone path planing.
I wonder if there is a way to limit the volume of the map to a certain distance around the drone's current location? So that it delete the old map far away?

Thank you in advance.
Chang

**Comment by ZacharyTaylor** [comment]
Yes this was added in a recent PR #174 
The parameter governing how far from the drone the map is stored is controlled by the parameter `max_block_distance_from_body`

**Comment by Changliu52** [comment]
Great! Perfect!
