### ISSUE TITLE
rviz can't visualize /voxblox_node/mesh

### ISSUE THREAD

**Issue by martinakos** [ethz-asl/voxblox#183]
I found [this](https://robotics.stackexchange.com/questions/15547/rviz-how-to-visualize-a-voxblox-mesh-as-a-markerarray) unanswered question online.  I'm in the same exact situation. 
I can run **roslaunch voxblox_ros cow_and_lady_dataset.launch** 
but then I can't visualize the mesh published by voxblox with rviz.

**Comment by martinakos** [comment]
I wasn't sourcing the corresponding setup.bash in the terminal that runs rviz

**Comment by ZacharyTaylor** [comment]
A little info as to why you need to source your workspace as the doc's were out of date.

The mesh is actually of type `voxblox_msgs::MeshBlock`. Voxblox use to output a standard MarkerArray, however this form of visualization means you have to output the entire mesh every time any part of it changes. This meant when running on a robot and visualizing on a laptop we were saturating our wifi connection to display even relatively small areas.

To correct this issue we made a custom message that supports partial updates only changing the mesh where needed. To use this custom message you have to build voxblox_rviz_plugin and have it in your workspace when running rviz.
