### ISSUE TITLE
How to load a pointcloud map that already existed?

### ISSUE THREAD

**Issue by Aryayay** [ethz-asl/voxblox#187]
Hi ,

I want to continue mapping with prebuilt point cloud map, is this supported in your code?

**Comment by ZacharyTaylor** [comment]
The loading and saving of voxel maps via protobuf is implemented and fully supported.
However, if you have a pointcloud that you wish to turn into a map this is slightly more difficult. The formation of TSDFs from pointclouds usually takes two inputs, the points and the location they were viewed from. In a pre-built pointcloud map this viewpoint information is missing and so some form of approximation to it would have to be generated (for example assuming points were viewed along their normals). This is not implemented but would not be too hard to add if there was sufficient interest in such a feature.

**Comment by Aryayay** [comment]
ok, its a goog idea!  Thx a lot.

**Comment by ZacharyTaylor** [comment]
Protobuf is a generic way of serializing data structures https://developers.google.com/protocol-buffers/
We use it for serialization of the TSDF map

**Comment by ZacharyTaylor** [comment]
To go from a pointcloud to a TSDF you need two pieces of information.
1) which scan each point in the pointcloud originally belonged to
2) the pose in the world frame the sensor had when it made each scan

You can approximate this, but a simple combined pointcloud would not have enough information by itself to create a TSDF

**Comment by plumewind** [comment]
Thank you very much for your reply, thank you, I understand now.

**Comment by joerowelll** [comment]
Has this been implemented in Voxblox?
