### ISSUE TITLE
How to measure the size of the Voxblox mesh map built?

### ISSUE THREAD

**Issue by Mayankm96** [ethz-asl/voxblox#197]
As the question suggests, I am trying to measure the size of the Voxblox mesh that has been built so that I can calculate the amount of area that has been explored by the UAV. 

Any idea on how to implement this?

**Comment by ZacharyTaylor** [comment]
It really depends what you mean by area and which representation you are using.

The easiest to calculate would be the viewed surface area, which would be as simple as iterating through the triangles and summing their area.

Another possibility would be to calculate the explored volume. If you are using the ply mesh output however this information has been lost. If you use the Mesh.msg a pretty good approximation to this can be given by the number of blocks with unique indexes multiplied by the volume of each block. However this is more easily done by counting blocks allocated in the actual voxblox map.

If you want 2D area, you can do the same as above but only consider the x and y component of the block when deciding if it is unique.
