### ISSUE TITLE
missing voxel.hallucinated = true ?

### ISSUE THREAD

**Issue by Magnusgaertner** [ethz-asl/voxblox#224]
As the comment of the function suggests, shouldn't these voxels be marked as hallucinated? 

https://github.com/ethz-asl/voxblox/blob/6cca5529f886cd6a1281d45d8db67bae648dcd8f/voxblox/include/voxblox/utils/planning_utils_inl.h#L87-L93

**Comment by helenol** [comment]
Yep good catch! :)
I'll fix it in the next PR.

**Comment by ZacharyTaylor** [comment]
Fixed in #225
