### ISSUE TITLE
Incorrect ESDF map  update from TSDF

### ISSUE THREAD

**Issue by rghl3** [ethz-asl/voxblox#246]
Hi Team,
   I built the voxblox repo in release mode. When I run in **fast** mode, the tsdf map is updated when I remove the obstacle. But the corresponding region is not being updated correctly in Esdf map. Am I missing any configuration settings?
```Parameters``` 
- voxel_size : 0.10
- tsdf_voxels_per_side : 16
- use_tf_transforms : true
- max_ray_length_m : 10.0
- esdf_max_distance_m : 5.0
- esdf_default_distance_m : 5.0
- use_const_weight : false
- allow_clear : true
- voxel_carving_enabled : true

Rest all are default parameters.

**Before placing obstacle** 
![initial_map](https://user-images.githubusercontent.com/43273198/54213400-5506a880-450a-11e9-89b9-d7d4a5ec982a.png)

**After Placing obstacle** 
![obstacle_map](https://user-images.githubusercontent.com/43273198/54213453-6ea7f000-450a-11e9-9069-26c4542827d6.png)

**After removing obstacle**
![obstacle_remove_map](https://user-images.githubusercontent.com/43273198/54213502-7e273900-450a-11e9-8497-7d56f2aaabbf.png)

Also another issue is when I rotate the robot_frame, the esdf pointcloud seems to be distinct for both the poses without merging.
![rotate_robot_map](https://user-images.githubusercontent.com/43273198/54213604-ae6ed780-450a-11e9-80b1-909b5f3a6d45.png)

The above issues persist even in merged mode too. 
Thank You.

**Comment by fabianbl** [comment]
@raghul9706 can you check if this improves if in the esdf integrator config, you set `min_distance_m` lower than the default value? (I'm not sure if this parameter is exposed in case you are using `voxblox_ros`, but you can change it directly here for a quick check: https://github.com/ethz-asl/voxblox/blob/master/voxblox/include/voxblox/integrator/esdf_integrator.h#L46)

**Comment by rghl3** [comment]
Hi @fabianbl ,
 Sorry for the late response. #259 seems to solve the issue for me with initial tests. Closing the issue. Thank You.
Regards,
Raghul
