### ISSUE TITLE
what's the difference between maplab and voxblox?

### ISSUE THREAD

**Issue by mechaliomar** [ethz-asl/voxblox#260]
maplab : https://github.com/ethz-asl/maplab

**Comment by mfehr** [comment]
after reading our papers again and a lot of discussions we came up with the following list of differences:
![image](https://user-images.githubusercontent.com/5071588/57580850-36dc0b00-74af-11e9-8bec-6edb8d66cc86.png)

Sources:
 - https://en.wikipedia.org/wiki/Sheep
 - https://en.wikipedia.org/wiki/Fox
 - https://arxiv.org/abs/1711.10250
 - https://helenol.github.io/publications/iros_2017_voxblox.pdf

**Comment by mechaliomar** [comment]
@mfehr Marius it's funny but so meaningful. Thanks

**Comment by HongLouyemeng** [comment]
> 



> after reading our papers again and a lot of discussions we came up with the following list of differences: ![image](https://user-images.githubusercontent.com/5071588/57580850-36dc0b00-74af-11e9-8bec-6edb8d66cc86.png)
> 
> Sources:
> 
> * https://en.wikipedia.org/wiki/Sheep
> * https://en.wikipedia.org/wiki/Fox
> * https://arxiv.org/abs/1711.10250
> * https://helenol.github.io/publications/iros_2017_voxblox.pdf

This reply is very beautiful!
