### ISSUE TITLE
Static camera + Moving Object?

### ISSUE THREAD

**Issue by eyildiz-ugoe** [ethz-asl/voxblox#275]
Hi,

Impressive work. We were wondering if the method also works with a static/non-moving camera with a moving object instead? Like to have the turn table rotate the object, and get the point cloud from a static camera meanwhile. Can we use this approach to model objects for instance? 

P.S: Assuming a working TF tree between the camera-world-turn-table.

**Comment by ZacharyTaylor** [comment]
We assume the mapped area is static, however this use case could probably be supported just by setting the world frame to the objects pose, as from the objects perspective you still have a static object and moving camera.
