### ISSUE TITLE
A question of TSDF/ESDF definition

### ISSUE THREAD

**Issue by im-Kitsch** [ethz-asl/voxblox#280]
Hi, I have a basic problem of the distance definition of TSDF/ESDF.  The distance is defined as from this point to nearest surface. But this distance, from point to surface, is defined as general geometriy definition, i.e. vertical distance or we don't assume that the surface is infinite by calculating the surface?

Like following 2D case, we assume Point C and Point A are respectively (0, 0) and (3, 4), and Point C is corner point of surface s_1 and s_2.

So the distance of point A in TSDF/ESDF are just 5 or 3, (directly form point A to C or from A to surface s_1 )

```
      
                                               Point A                        

surface s_1
--------------------------------- C
                                 |
                                 |      surface s_2
                                 |
                                 |
```

**Comment by ZacharyTaylor** [comment]
We only measure to observed points. For the ESDF the distance in the example is 5. The TSDF uses a projective distance measure and so will give a value that is greater than or equal to 5.

**Comment by resplendent-star** [comment]
> We only measure to observed points. For the ESDF the distance in the example is 5. The TSDF uses a projective distance measure and so will give a value that is greater than or equal to 5.

hello，do  you  mean  the  TSDF distance of  point A，is  let  a  ray  light  come  from  camera optical  center  to  point  A，and  obviously   this ray  will have  an  intersection   【point  I】in  a  surface，and  the  TSDF distance is  Euclidean distance  between  I and  A

**Comment by im-Kitsch** [comment]
Thanks for the help.  :)
