### ISSUE TITLE
Points disappearing from mesh

### ISSUE THREAD

**Issue by oleg-alexandrov** [ethz-asl/voxblox#303]
I am running a bot with a depth camera and showing the VoxBlox simulated mesh in RVIZ. As the bot gets closer to a wall, the VoxBlox mesh actually starts losing points and even larger areas. This is a bit counter-intuitive, as getting closer should make the results more accurate.

I guess some filtering may be happening somewhere, but the documentation and the paper is not clear about that. I did try to play with the voxtel size, truncation distance, and the method (fast vs merged vs simple). 

I am not particularly close or far from the wall, on the order of 1-2 meters. The voxtel size is 0.01 to 0.02. Any thoughts?

**Comment by oleg-alexandrov** [comment]
I take it back. The issue was on my side.

**Comment by maffan-96** [comment]
Hey, what was the issue on your side?

**Comment by oleg-alexandrov** [comment]
Something was wrong with the external simulator logic, so bad data was fed to VoxBlox.
