### ISSUE TITLE
No visualization on rviz

### ISSUE THREAD

**Issue by aaravrav142** [ethz-asl/voxblox#306]
Hi, 

I correctly build the package and tried to run the cow and lady dataset using 
`roslaunch voxblox_ros cow_and_lady_dataset.launch`

On launching rviz and keeping fixed frame as '`world`' and using the voxblox plugin `/voxblox_node/mesh`, nothing displays on the rviz screen. On the console however everything seems to run fine. 
How can I solve this issue. Any help would be useful. Thanks

**Comment by XanxusCrypto** [comment]
I met the same problem. Waiting for some help. Thanks for sharing.

**Comment by nachovizzo** [comment]
That's because you didn't source the devel space before launching rviz most likely
Just `source ~/catkin_ws/devel/setup.bash` and then launch `rviz` . Now you would be able to see the rviz plugin built by the voxblox package

**Comment by Hao-Starrr** [comment]
@nachovizzo Thanks! It is helpful. 
@Tokymin I have the visualization, but it can only display the message after rviz get prepared. If I hide the map, and displace it again, the previous map will not occur. So make sure you set up rviz first and then run the launch file.

**Comment by Xue1iang** [comment]
Source /workspace/devel/setup.bash doesn't help......VoxbloxMesh in Rviz sill shows nothing.
