### ISSUE TITLE
Maximum update frequency of maps 1Hz

### ISSUE THREAD

**Issue by biancabndris** [ethz-asl/voxblox#312]
Hello, 

First of all, thanks for making this repository open source! It has been quite easy working with it.
 
I have an issue though, I cannot make the update frequency of the maps (either TSDF or ESDF) lower than 1 Hz. I am running the _esdf_server_ and try to set the _update_mesh_every_n_sec_ to a lower value but the most I can get is 1Hz. 

The incoming point cloud is very small and the time it takes to process and integrate it is definitely lower than 1 s. Also, I set the _voxel_size_ to a big value so that all operations consume less time. With all this, the overall frequency is always 1 Hz. 

Is this a bottleneck or is there any parameter that I can configure?

Many thanks in advance.

**Comment by yuliangzhong** [comment]
Hello, I have this question, too. 

Did you find a solution? Could you post it here? Thanks a lot.
