### ISSUE TITLE
No mesh via Rviz

### ISSUE THREAD

**Issue by LanWu076** [ethz-asl/voxblox#331]
I can see messages received via Rviz but there is no mesh showing on my screen. I'm using cow and lady dataset. The fixed frame is "world". I do have a warning said: No tf data. Actual error:Fixed Frame [world] does not exist. 
Does anybody know what could be wrong?

![Screenshot from 2020-06-30 15-51-30](https://user-images.githubusercontent.com/50563173/86093668-b0d7b500-baf2-11ea-9281-a37bada2eca7.png)

**Comment by tyxxj** [comment]
Hello, try to source your workspace first on the terminal that you will run rviz

**Comment by guoxiaoyang12** [comment]
Have you fixed this problem? I have same porblem

**Comment by apache8080** [comment]
I am running into the same issue with every launch file except for basement.
