### ISSUE TITLE
Is it possible to disable the ESDF generation?

### ISSUE THREAD

**Issue by apache8080** [ethz-asl/voxblox#342]
As the title suggests, I was wondering if it is possible to use voxblox for just the TSDF and mesh generation. Looking at the architecture it seems like it is possible but want to make sure.

**Comment by alexmillane** [comment]
Yes that is very possible, it's probably the default mode of operation. Our main example "cow_and_lady_dataset.launch" launches a tsdf_server (as opposed to an esdf_server) which will not compute an ESDF.
