### ISSUE TITLE
Error build in Ubutu 16.04, ROS Kinetic

### ISSUE THREAD

**Issue by hai-h-nguyen** [ethz-asl/voxblox#353]
I got this error when build on ROS Kinetic:

No rule to make target '/usr/lib/x86_64-linux-gnu/libvtkproj4-6.2.so.6.2.0'

How to get rid of it?

**Comment by alexmillane** [comment]
What was the solution here? For other people encountering the same issue?

**Comment by hai-h-nguyen** [comment]
Yeah, the solution is to create a symlink. In my case:

```sudo ln -s /usr/lib/x86_64-linux-gnu/libvtkCommonCore-6.2.so /usr/lib/x86_64-linux-gnu/libvtkproj4-6.2.so```

The name libvtkproj4-6.2.so might depend on the version, but it will be the thing that the compiler complains about.

**Comment by alexmillane** [comment]
Cheers for that. Hopefully this can help someone down the line :)
