### ISSUE TITLE
Remove vertex indices from Meshes

### ISSUE THREAD

**Issue by helenol** [ethz-asl/voxblox#44]
Appear to not be used or necessary anywhere. Also strictly increasing all the time.

@alexmillane

**Comment by mklingen** [comment]
When we wrote the meshing code for OpenChisel, the meshes were originally being used in an opengl ES renderer on the device. When doing this its efficient to have a flat array of floats as the vertex positions / colors indexed by shorts. When we cut out the opengl renderer for the open source version and just started visualizing through RVIZ (which doesn't support indexing), we just passed around vertexes with the assumption that the index buffer is just increasing.

**Comment by ZacharyTaylor** [comment]
With the merge of #79 the vertex indices are no longer always just an increasing list. They now need to be kept so that mesh connectivity information can be made available.

**Comment by ZacharyTaylor** [comment]
Closing as they are now needed
