### ISSUE TITLE
Add check for zero-ray bug

### ISSUE THREAD

**Issue by mfehr** [ethz-asl/voxblox#68]
If there is a point that is too close to the camera origin, the ray tracing just goes on forever and crashes due to a bad_alloc

We should really add a check for this!

**Comment by helenol** [comment]
This is already checked for:
https://github.com/ethz-asl/voxblox/blob/master/voxblox/include/voxblox/integrator/tsdf_integrator.h#L145

**Comment by ZacharyTaylor** [comment]
#104 fixes this, as it uses length along ray to terminate
