### ISSUE TITLE
max_ray_length_m not used properly with all integrators

### ISSUE THREAD

**Issue by skohlbr** [ethz-asl/voxblox#94]
The `max_ray_length_m` param is used properly with the simple integrator, but the merged integrator ignores it. When for instance using VLP-16 clouds as input this becomes apparent really fast as integration time gets very slow with clouds containing points tens of meters away.

**Comment by ZacharyTaylor** [comment]
I did some tests the other day and the merge integrator was definitely using it, I will check and see if anythings changed

**Comment by skohlbr** [comment]
Took a look and created PR #97 to fix the issue. The parameter was indeed used, but only if `allow_clear` was set to `true`. Otherwise, it was ignored, which lead to all rays getting integrated regardless if they exceed the specified max distance (making things super slow when using high range LIDARs).
