### ISSUE TITLE
linter takes issue with the header names

### ISSUE THREAD

**Issue by ZacharyTaylor** [ethz-asl/voxblox#96]
A current header is for example:
VOXBLOX_CORE_ESDF_MAP_H_

and linter will prevent commits unless it is changed to:
CORE_ESDF_MAP_H_

**Comment by helenol** [comment]
Hmm this is incorrect, and a problem with the linter. @mfehr ? Can we either turn this feature off or fix it?

**Comment by mfehr** [comment]
I'll look into it tomorrow. For now just fix whatever makes sense, then use the -n switch

**Comment by mfehr** [comment]
This should be fixed #101
